name: vue-admin-api
services:
  mysql:
    networks:
      - vue-admin-api-network
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=vue-admin-api
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    networks:
      - vue-admin-api-network
    image: redis:7.4
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
  rabbitmq:
    networks:
      - vue-admin-api-network
    image: rabbitmq:4.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
  meilisearch:
    networks:
      - vue-admin-api-network
    image: getmeili/meilisearch:v1.13.3
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=Pqq-IQRvyGgk4TT60glCapPIAUOD6SraSC86PUU_Djk
    ports:
      - '7700:7700'
    volumes:
      - ./data/meili_data:/meili_data

networks:
  vue-admin-api-network:
    driver: bridge
